### ISSUE TITLE
Mismatching clicks

### ISSUE THREAD

**Issue by StrangePan** [Threekoolkatz/GUI-PA-1#11]
Clicking to select a point causes a strange "jump" to occur the next time the graph is drawn; you end up not clicking the data point you had your mouse over.

**Comment by StrangePan** [comment]
Issue appears to be caused by the labels that display selected data point information expanding the window, causing the graph to unexpectedly resize. This is a layout issue. Somehow we need to make the labels not force a resize on the window.

**Comment by Deaboy** [comment]
The issue appears to be related to the window layout. When selecting a data point, the labels that display the information at that data point cause the window to resize underneath the cursor, causing everything to be just a little bit off.
