### ISSUE TITLE
Day, month, year radio buttons distorting graph

### ISSUE THREAD

**Issue by StrangePan** [Threekoolkatz/GUI-PA-1#12]
Something's not quite right with these... switching between them doesn't scale the range bounds appropriately. Play with them for a bit to see what I mean.

**Comment by Kiwii12** [comment]
Is this still a problem, many things have changed

**Comment by Threekoolkatz** [comment]
It looks like it scales it correctly to me?  Screenshot would help.

**Comment by StrangePan** [comment]
Yes, this is still an issue
1. load up some data
2. click "year"
3. zoom out and pan around a bit
4. click "month"
5. click "year"
6. zoom out; graph should be a line

**Comment by Threekoolkatz** [comment]
I must not be doing it right, because its scaling fine.  No line or any weird distortion
