### ISSUE TITLE
AverageData NullPointerException

### ISSUE THREAD

**Issue by StrangePan** [Threekoolkatz/GUI-PA-1#18]
Some data points may return `null`; this class (and all statistic functions) need to take this into account.

Note: when calculating the average, if a data point returns `null`, then the counter should not be incremented in that case. There will need to be multiple counters for each metric (temperature, humidity, etc).

**Comment by Kiwii12** [comment]
Fixed some of the stuff for sure, needs more testing before closed though

**Comment by Kiwii12** [comment]
also only two counters were needed because only temp and wind speed are averaged.
